plugin: aws_ec2
regions:
  - us-east-1

filters:
  instance-state-name: running

keyed_groups:
  - key: tags.Name
    prefix: ""
  - key: tags.Group
    prefix: ""
    separator: ""

compose:
  ansible_host: public_ip_address
  ansible_user: ec2-user                 
  ansible_ssh_private_key_file: /home/ec2-user/ansible-notes-app/newkey.pem

